### ISSUE TITLE
申请使用仓库代码

### ISSUE THREAD

**Issue by da1234cao** [RealLeooo/phpbeginner_gmanage#13]
我是湖南大学软件安全课程的学生助教。搭建一个网站，**仅用于**学生练习攻击。
网址：http://115.157.201.179:5000/phpbeginner/login.php
<br>
https://github.com/da1234cao/software_security_class/tree/master/DVWA%E6%8C%87%E5%8C%97
上面连接的说明文档中**会注明phpbeginner代码的出处**。
<br>
目前网址没有对学生公开，**希望得到您的同意**。
不同意的话，我会立即从上面网址中将代码移除。目前的搭建，仅用于尝试代码可以运行。
<br>
谢谢～

**Comment by udoless** [comment]
可以的------------------ 原始邮件 ------------------发件人: da1234cao  <notifications@github.com>发送时间: 2020年10月11日 11:10收件人: udoless/phpbeginner_gmanage <phpbeginner_gmanage@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[udoless/phpbeginner_gmanage] 申请使用仓库代码 (#13)
我是湖南大学软件安全课程的学生助教。搭建一个网站，仅用于学生练习攻击。
网址：http://115.157.201.179:5000/phpbeginner/login.php

https://github.com/da1234cao/software_security_class/tree/master/DVWA%E6%8C%87%E5%8C%97
上面连接的说明文档中会注明phpbeginner代码的出处。

目前网址没有对学生公开，希望得到您的同意。
不同意的话，我会立即从上面网址中将代码移除。目前的搭建，仅用于尝试代码可以运行。

谢谢～

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/udoless/phpbeginner_gmanage/issues/13",
"url": "https://github.com/udoless/phpbeginner_gmanage/issues/13",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
